- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Add unetbootin repo
      apt_repository:
        repo: ppa:gezakovacs/ppa

    - name: install packages
      apt:
        update_cache: yes
        state: present
        name:
          - git
          - tree
          - htop
          - ansible-lint
          - curl
          - git-extras
          - unetbootin
          - tmux
          - google-chrome-stable
          - unetbootin
          - fzf

- name: install and setup docker
  hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
    - feycot
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Install and setup zsh
  hosts: all
  roles:
    - role: gantsign.oh-my-zsh
      oh_my_zsh_install: yes
      users:
        - username: feycot
          oh_my_zsh:
            theme: murilasso
            plugins:
              - git
              - docker
              - docker-compose
              - fzf
              - git-extras
              - heroku
              - laravel
              - tmux
  tasks:
    - name: Set zsh
      become: yes
      user:
        name: feycot
        shell: /bin/zsh

- name: Install Github Cli
  hosts: all
  tasks:
    - name: Install github3.py
      pip:
        name: github3.py
        state: present

    - name: Install Github CLI
      include_role:
        name: iancleary.github_cli
      vars:
        gh_arch: "amd64"

- name: Setup git config
  hosts: all
  tasks:
    - name: Set global user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: feycot@gmail.com

    - name: Set global user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: feycot

    - name: Setup aliases to ~/.gitconfig
      community.general.git_config:
        name: "alias.{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: co, value: checkout }
        - { name: ci, value: commit }
        - { name: st, value: status }
        - { name: br, value: branch }
        - { name: hist, value: "log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" }
        - { name: type, value: 'cat-file -t' }
        - { name: dump, value: 'cat-file -p' }
        - { name: commend, value: 'commit --amend' }

    - name: Set vim as editor
      community.general.git_config:
        name: core.editor
        scope: global
        value: vim

    - name: Copy git global ignore file
      copy:
        src: files/gitignore_global
        dest: "~/.gitignore_global"

    - name: Set global gitignore
      community.general.git_config:
        name: core.excludesFile
        scope: global
        value: ~/.gitignore_global

- name: Install deps to build PHP via asdf
  hosts: all
  become: yes
  tasks:
    - name: install deps for php
      apt:
        name: [autoconf, bison, build-essential, curl, gettext, git, libgd-dev, libcurl4-openssl-dev, libedit-dev,
        libicu-dev, libjpeg-dev, libmysqlclient-dev, libonig-dev, libpng-dev, libpq-dev, libreadline-dev, libsqlite3-dev,
        libssl-dev, libxml2-dev, libzip-dev, openssl, pkg-config, re2c, zlib1g-dev]

- name: Install asdf and plugins
  hosts: all
  roles:
    - role: markosamuli.asdf
      asdf_init_shell: true
      asdf_plugins:
        - name: "ruby"
          versions: ["3.0.1"]
          global: "3.0.1"

        - name: "nodejs"
          versions: ["16.3.0", "15.14.0", "14.17.0"]
          global: "16.3.0"

        - name: "php"
          versions: ["8.0.7"]
          global: "8.0.7"

- name: Install snaps
  hosts: all
  tasks:
    - name: Install Snaps packages
      become: yes
      community.general.snap:
        name:
          - zoom-client
          - ngrok
          - postman
          - telegram-desktop

    - name: Install snaps classlic
      become: yes
      community.general.snap:
        classic: yes
        name: [code, heroku, slack, sublime-text, phpstorm]

- name: Install virtualbox and vagrant
  hosts: all
  roles:
    - fey.install_virtualbox_vagrant

- hosts: all
  become: true
  roles:
    - role: diodonfrost.terraform
