name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo useradd -m feycot
          sudo make install-ansible
          cd ansible && ansible-playbook -i hosts  playbook.yml  -vv

      - name: Test
        run: make prepare-ubuntu

      - name: Linter
        run: make lint
